import { Inter } from 'next/font/google';
import { Banner } from './_components/banner';
import { Nav } from './_components/nav';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Netflix Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header>
          <Nav />
          <Banner />
        </header>
        {children}
      </body>
    </html>
  );
}
